# Generated by Django 5.1.7 on 2025-03-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_useruniversitymatch_address_useruniversitymatch_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/resumes'),
        ),
    ]
