# Generated by Django 5.1.7 on 2025-03-27 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_userprofile_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('graduation_rate', models.FloatField()),
                ('sat_score', models.IntegerField()),
                ('organization_type', models.CharField(max_length=100)),
                ('financial_aid', models.BooleanField(default=False)),
                ('area', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('IN_REVIEW', 'In Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WAITLISTED', 'Waitlisted')], default='APPLIED', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.college')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'college')},
            },
        ),
    ]
