# Generated by Django 5.1.7 on 2025-03-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_userapplication_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnalysisDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tenth_marks_received', models.FloatField()),
                ('tenth_marks_total', models.FloatField(default=100)),
                ('twelfth_marks_received', models.FloatField()),
                ('twelfth_marks_total', models.FloatField(default=100)),
                ('sat_score_received', models.IntegerField(blank=True, null=True)),
                ('sat_score_total', models.IntegerField(blank=True, default=1600, null=True)),
                ('other_exam_score', models.TextField(blank=True, null=True)),
                ('avg_cgpa', models.FloatField(blank=True, null=True)),
                ('competition_name', models.CharField(blank=True, max_length=200, null=True)),
                ('learning_experience', models.TextField(blank=True, null=True)),
                ('extra_curricular', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('classification', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
