# Generated by Django 5.1.7 on 2025-04-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_university_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
