# Generated by Django 5.1.7 on 2025-04-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_university_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='financial_aid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='graduation_rate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='sat_score',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
