# Generated by Django 5.1.7 on 2025-04-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_university_financial_aid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='net_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
