# Generated by Django 5.1.7 on 2025-04-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_university_net_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
