# Generated by Django 5.1.7 on 2025-05-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_university_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='logo2_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='university_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
